# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kinin Blog
email: nandafransiska.mail@gmail.com
description: >
  Kinin.web.id adalah sebuah blog personal populer tempat belajar blogging,
  tutorial, berita terbaru seputar teknologi dan game center.
logo: "/assets/images/fav.ico"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kinin.web.id" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage
permalink: /:title/ #permalink hanya menampilkan judul
name: 'Nanda Fransiska'
bio: >
  Halo, saya Nanda author dari blog kinin.web.id - saya senang berlajar
  tentang blogging, dan berbagi melalui artikel. Jangan lupa kunjungi
  blog Kinin untuk mendapatkan artikel lainnya.
author_image: "/assets/images/author.webp"
twitter_username: jekyllrb
github_username:  jekyll

# Google Analytics
analytics_id: ""

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: kinin 

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate

